### ISSUE TITLE
Fix issue with Container Service 3.6.0 update

### ISSUE THREAD

**Issue by HChughtai** [UCL-MIRSG/ansible-collection-infra#140]
### Short Description

Integration test is failing when trying to update Container Service

- https://github.com/UCL-MIRSG/ansible-collection-infra/pull/135

### Evidence/Steps to Reproduce

- Run the install XNAT playbook on the branch with updated Container Service >= 3.5.0
- Communication from XNAT to Docker server fails

### Acceptance Criteria/Expected Behaviour

- Run the install XNAT playbook on the branch with updated Container Service >= 3.5.0
- Communication from XNAT to Docker server succeeds
- All tests pass

**Comment by HChughtai** [comment]
I've tried running t[he molecule tests for the install xnat playbook locally](https://github.com/UCL-MIRSG/ansible-collection-infra#test-a-playbook), but keep hitting general network issues when downloading components

**Comment by HChughtai** [comment]
This may be a similar issue: https://groups.google.com/g/xnat_discussion/c/yJZYYkEdchg/m/84y707MCAwAJ

**Comment by p-j-smith** [comment]
I think the original issue was due to incompatibility between plugins with the latest version of XNAT. If we [deploy only the Container Service and Batch Launch plugins](https://github.com/UCL-MIRSG/ansible-collection-infra/pull/135/commits/ee8617470de05035c505e8d85d94f53d446dd264), we're still unable to add a docker host but the error we get is different.

I've opened a [discussion](https://groups.google.com/g/xnat_discussion/c/h1ODNrTIQnY) on the forum to see if the developers have any ideas what the issue is.

**Comment by p-j-smith** [comment]
We will need to switch the [container service host](https://github.com/UCL-MIRSG/ansible-collection-infra/blob/18bd51788d8d92be28d3ab8a5eafe879f8692d46/roles/xnat_container_service/tasks/main.yml#L47-L49) to use `tcp` rather than `https`. However, this currently leads to a different issue when using TLS (the container service doesn't set `DOCKER_TLS_VERIFY` so it tries to connect via HTTP instead of HTTPS). Looks like we have two options for now:
1. don't use TLS on our Docker host
2. wait for the Container Service to be patched and a new release made
